# Generated by Django 4.2.4 on 2023-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcomment_choosen_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='choosen_blog',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='choosen_blog',
            field=models.ManyToManyField(blank=True, default=None, to='blog.blog'),
        ),
    ]
