# Generated by Django 4.2.4 on 2023-09-01 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_profile_picture_alter_about_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
