# Generated by Django 4.2.4 on 2023-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
